fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MiguelAlcaino\MindbodyPaymentsBundle\Entity\User
    from_email:
        address: "%env(MINDBODY_MAILER_USER)%"
        sender_name: "%env(MINDBODY_MAILER_USER)%"