parameters:
    mindbody_source_name: '%env(MINDBODY_SOURCE_NAME)%'
    mindbody_source_password: '%env(MINDBODY_SOURCE_PASSWORD)%'
    mindbody_admin_user: '%env(MINDBODY_ADMIN_USER)%'
    mindbody_admin_password: '%env(MINDBODY_ADMIN_PASSWORD)%'
    mindbody_site_ids: '%env(json:MINDBODY_SITE_IDS)%'
    router.request_context.host: '%env(HOST)%'
    router.request_context.scheme: https
    router.request_context.base_url: ''

services:
    _defaults:
        public: false

    #SERVICES
    guzzle.client:
        class: GuzzleHttp\Client

    file_cache_service:
        class: Symfony\Component\Cache\Simple\FilesystemCache

    Symfony\Component\Cache\Simple\FilesystemCache: '@file_cache_service'

    miguel_alcaino.mb_api:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MB_API
        arguments:
            $sourceName: '%mindbody_source_name%'
            $password: '%mindbody_source_password%'
            $siteIds: '%mindbody_site_ids%'

    ### MINDBODY SOAP REQUESTERS ###

    miguel_alcaino.minbody.credentials:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\Credentials\MindbodyCredentialsService
        arguments:
            - '@parameter_bag'

    miguel_alcaino.mindbody.soap.request:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\MindbodySOAPRequester
        arguments:
            - '@miguel_alcaino.minbody.credentials'
            - '@guzzle.client'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\MindbodySOAPRequester: '@miguel_alcaino.mindbody.soap.request'

    miguel_alcaino.mindbody.soap.request.sale_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\SaleServiceSOAPRequest
        arguments:
            - '@miguel_alcaino.mindbody.soap.request'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\SaleServiceSOAPRequest: '@miguel_alcaino.mindbody.soap.request.sale_service'

    miguel_alcaino.mindbody.soap.request.site_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\SiteServiceSOAPRequest
        arguments:
            - '@miguel_alcaino.mindbody.soap.request'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\SiteServiceSOAPRequest: '@miguel_alcaino.mindbody.request_handler.site_service'

    miguel_alcaino.mindbody.soap.request.class_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\ClassServiceSOAPRequester
        arguments:
            - '@miguel_alcaino.mindbody.soap.request'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\ClassServiceSOAPRequester: '@miguel_alcaino.mindbody.soap.request.class_service'

    miguel_alcaino.mindbody.soap.request.client_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\ClientServiceSOAPRequester
        arguments:
            - '@miguel_alcaino.mindbody.soap.request'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodySOAPRequest\ClientServiceSOAPRequester: '@miguel_alcaino.mindbody.soap.request.client_service'

    ### END MINDBODY SOAP REQUESTERS ###

    ### MINDBODY REQUEST HANDLERS ###

    miguel_alcaino.mindbody.request_handler.sale_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\SaleServiceRequestHandler
        arguments:
            - '@miguel_alcaino.mindbody.soap.request.sale_service'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\SaleServiceRequestHandler: '@miguel_alcaino.mindbody.request_handler.sale_service'

    miguel_alcaino.mindbody.request_handler.site_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\SiteServiceRequestHandler
        arguments:
            $mb: '@miguel_alcaino.mb_api'
            $cache: '@file_cache_service'
            $siteServiceSOAPRequest: '@miguel_alcaino.mindbody.soap.request.site_service'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\SiteServiceRequestHandler: '@miguel_alcaino.mindbody.request_handler.site_service'

    miguel_alcaino.mindbody.request_handler.client_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\ClientServiceRequestHandler
        arguments:
            - '@miguel_alcaino.mindbody.soap.request.client_service'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyRequestHandler\ClientServiceRequestHandler: '@miguel_alcaino.mindbody.request_handler.client_service'

    ### END MINDBODY REQUEST HANDLERS ###

    miguel_alcaino.mindbody_service:
        public: true
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyService
        arguments:
            $mb: '@miguel_alcaino.mb_api'
            $cache: '@file_cache_service'
            $logger: '@logger'
            $params: '@parameter_bag'
            $fromSessionService: '@miguel_alcaino.mindbody.from_session'
            $siteServiceRequestHandler: '@miguel_alcaino.mindbody.request_handler.site_service'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyService: '@miguel_alcaino.mindbody_service'

    miguel_alcaino.mindbody.country_and_city_service:
        class:  MiguelAlcaino\MindbodyPaymentsBundle\Service\CountryAndCitiesService

    MiguelAlcaino\MindbodyPaymentsBundle\Service\CountryAndCitiesService: '@miguel_alcaino.mindbody.country_and_city_service'

    miguel_alcaino.mindbody.transaction_record.factory:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\Factory\TransactionRecordFactory

    MiguelAlcaino\MindbodyPaymentsBundle\Service\Factory\TransactionRecordFactory: '@miguel_alcaino.mindbody.transaction_record.factory'

    miguel_alcaino.mindbody.transaction_record_filler:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\TransactionRecord\TransactionRecordFillerService
        arguments:
            - '@miguel_alcaino.mindbody.from_session'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\TransactionRecord\TransactionRecordFillerService: '@miguel_alcaino.mindbody.transaction_record_filler'

    miguel_alcaino.mindbody.from_session:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\FromSessionService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\FromSessionService: '@miguel_alcaino.mindbody.from_session'

    miguel_alcaino.mindbody.within_ten_years_validator:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\Validator\WithinTenYearsValidatorService
        arguments:
            $translatorService: '@translator'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\Validator\WithinTenYearsValidatorService: '@miguel_alcaino.mindbody.within_ten_years_validator'

    miguel_alcaino.mindbody.customer_filler:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\Customer\CustomerFillerService
        arguments:
            - '@miguel_alcaino.mindbody.from_session'
            - '@miguel_alcaino.mindbody_service'
            - '@doctrine.orm.entity_manager'
    MiguelAlcaino\MindbodyPaymentsBundle\Service\Customer\CustomerFillerService: '@miguel_alcaino.mindbody.customer_filler'

    miguel_alcaino.mindbody.user_session_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\UserSessionService
        arguments:
            $fromSessionService: '@miguel_alcaino.mindbody.from_session'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\UserSessionService: '@miguel_alcaino.mindbody.user_session_service'

    miguel_alcaino.mindbody.program_service:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyProgramService
        arguments:
            $parameterBag: '@parameter_bag'
            $siteServiceRequestHandler: '@miguel_alcaino.mindbody.request_handler.site_service'

    MiguelAlcaino\MindbodyPaymentsBundle\Service\MindbodyProgramService: '@miguel_alcaino.mindbody.program_service'

    ### REPOSITORY ###

    MiguelAlcaino\MindbodyPaymentsBundle\Repository\LocationRepository:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Repository\LocationRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    MiguelAlcaino\MindbodyPaymentsBundle\Repository\ProductRepository:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Repository\ProductRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    MiguelAlcaino\MindbodyPaymentsBundle\Repository\CustomerRepository:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Repository\CustomerRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    MiguelAlcaino\MindbodyPaymentsBundle\Repository\ProgramRepository:
        class: MiguelAlcaino\MindbodyPaymentsBundle\Repository\ProgramRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    ### END REPOSITORY ###